# Adding a comment cuz
image: python:3.5

variables: 
    GIT_STRATEGY: fetch
    GIT_SUBMODULE_STRATEGY: none
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - .local/share/virtualenvs/raspberry-pi-kwz-7fxL

before_script:
    - python -V
    - pip install pipenv
    - pipenv install --dev --skip-lock

stages:
    - build
    - test
    - deploy
    - release

setup:
    stage: build
    script:
        - python setup.py sdist
    artifacts:
        paths:
            - dist/
    only:
        - master

pytest:
    stage: test
    script:
        - pipenv run python -m pytest --ignore=autogen-api-commands -vvv

staging:
    stage: deploy
    dependencies:
        - setup
    script:
        # TODO update version
        - twine upload --repository-url https://push.fury.io/sphero -u TOKEN -p "" dist/*
    when: manual
    only:
        - web
        - master

production:
    stage: release
    dependencies:
        - setup
    script:
        - python -V
        # TODO upload to PyPI
    when: manual
    only:
        - web
