image: python:3.5

variables: 
    GIT_STRATEGY: fetch
    GIT_SUBMODULE_STRATEGY: none
    PIP_CACHE_DIR: ".cache/pip"
    PIPENV_VENV_IN_PROJECT: "true"

cache:
  paths:
    - .cache/pip
    - .venv

before_script:
    - python -V
    - pip install pipenv
    - pip install pytest
    - pip install pylint
    - pipenv install --dev --skip-lock

stages:
    - linting
    - build
    # TODO: Fix broken pipeline by fixing pytest process.  Bypassing for now.
    #- test
    # TODO: skipping deployment until further notice.
    #- deploy
    #- release

    stage: linting
    allow_failure: false
    script: pylint --disable=R,C,W spheroboros/*.py
    
setup:
    stage: build
    script:
        - python setup.py sdist
        - ls -al

    artifacts:
        paths:
            - dist/
    only:
        - master

# TODO: change spheroboros to sphero_sdk
#pytest:
#    stage: test
#    script:
#        - pipenv run python -m pytest --ignore=autogen-api-generators -vvv
#
#staging:
#    stage: deploy
#    dependencies:
#        - setup
#    script:
#        # TODO update version
#        - pipenv run twine upload --repository-url https://push.fury.io/sphero -p "" dist/*
#    when: manual
#    only:
#        - web
#        - master
#
#production:
#    stage: release
#    dependencies:
#        - setup
#    script:
#        - python -V
#        # TODO upload to PyPI
#    when: manual
#    only:
#        - web
