image: python:3.5

variables: 
    GIT_STRATEGY: fetch
    GIT_SUBMODULE_STRATEGY: none
    PIP_CACHE_DIR: ".cache/pip"
    PIPENV_VENV_IN_PROJECT: "true"

cache:
  paths:
    - .cache/pip
    - .venv

before_script:
    - python -V
    - pip install pipenv
    - pip install pytest
    - pip install pylint
    - pipenv install --dev --skip-lock

stages:
    - linting
    - test
#    - deploy
#    - release

pylint:
    stage: linting
    allow_failure: false
    script: pylint --disable=R,C,W sphero.py

pytest:
    stage: test
    script:
        - pipenv run python -m pytest --ignore=autogen-api-generators -vvv

